name: "Run Checkov"
description: "Run Checkov infrastructure as code scanner"
inputs:
  directory:
    description: "Directory to scan"
    required: false
    default: "."
  file:
    description: "File to scan"
    required: false
  skip_check:
    description: "Checks to skip (comma separated)"
    required: false
runs:
  using: "composite"
  steps:
    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ${{ inputs.directory }}
        file: ${{ inputs.file }}
        skip_check: ${{ inputs.skip_check }}
        framework: terraform
