name: "Get Version"
description: "Get the version of the image / set a new version"
outputs:
  version:
    description: "The version"
    value: ${{ steps.version.outputs.version }}
  version_tag:
    description: "The version tag"
    value: ${{ steps.version.outputs.version_tag }}

runs:
  using: "composite"
  steps:
    - name: Get version
      id: version
      uses: paulhatch/semantic-version@v5.4.0
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}"
        change_path: "."

